### ISSUE TITLE
Enable modules snapshot for Android

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/NativeScript#1563]
# The Story
In a nutshell - since in Android application loading time is one of the areas that need improvement,
we've made a POC implementation that takes advantage of V8's [startup snapshots](http://v8project.blogspot.bg/2015/09/custom-startup-snapshots.html) feature to see what may be achieved with it. The results are quite promising and we may gain literally more than **1 second !** of an improvement by saving all the modules.

# Technical Details
Due to the V8 API specifics, we need to bundle the entire modules JS into one single file and pass it to the [V8::CreateSnapshotDataBlob](http://v8.paulfryzel.com/docs/master/classv8_1_1_v8.html#a05f6c30582cc654b5fb09fab98a0dbbb) method. What V8 does when making the snapshot is to parse, compile and run this script into a new Context and then to save the state of the heap into a binary representation. Then, upon next application runs, this binary file may be used to load the whole representation of the modules directly within memory. 

Here is my proposal for taking advantage of this feature:

# Distribute pre-generated BLOBs
The snapshot is CPU-architecture dependent. Hence, if we want to distribute pre-generated version of the snapshot we will need to package three files, saved against the three available architectures - `armeabi-v7a`, `x86` and `arm64-v8a`. The average size of one file is ~3 MB but it compresses very well and an archived version is about 400 KB. 

**This is the most efficient way performance-wise. It adds further optimization by skipping the extraction of numerous JS files initially**

# Tasks:
- [x] Ensure modules are snapshot-ready. This is already done - https://github.com/NativeScript/NativeScript/pull/1407
- [x] Write a custom bundler that puts all the modules content within a single JS file. I've already done a custom Node task for the POC but we may go with [webpack](https://webpack.github.io/) for example (as @hdeshev) suggested.
- [x] Think how to automate snapshot generation against the three CPU architectures.
- [x] Think how to distribute (package) these three binary files. For example we may have two packages - `tns-core-modules` and `tns-core-modules-snapshot`. Or we may package all into one package.
- [x] Since the debugger does not work with snapshots, we will need to rely on the snapshot for release builds ONLY. Hence, there will be some effort on the CLI side. Plus, for release builds the CLI should not pack the modules JavaScript files but only the BLOBs  (ping @teobugslayer, @ligaz).
- [x] Enable the Android Runtime to consume such a BLOB directly, depending on the current CPU architecture. We may use the same convention as for the native part of the Runtime itself, for example:

    ```
    tns_modules
    ├── snapshot
    │   ├── armeabi-v7a
    │   │   ├── snapshot.blob
    │   ├── arm64-v8a
    │   │   ├── snapshot.blob
    │   ├── x86
    │   │   ├── snapshot.blob
    
    ```

**Comment by NathanaelA** [comment]
Please allow the CLI to be able to (optionally?) generate the BLOB also; if I am bundling a dozen plugins; their is no reason why I shouldn't be able to get the speed enhancement by creating my own BLOB's with all my modules on Android.

**Comment by x4080** [comment]
Snapshot generation can be generated on pc or have to be on device? If have to be on device, for start maybe the developer can manually use command or put some kinda function to generate it then send it back for deployment 

If this is greatly improve things up, even if this is the only way, i will still be happy :)

**Comment by vjoao** [comment]
Can this be extended to put the actual app code inside the blob?

**Comment by fealebenpae** [comment]
I would suggest investigating whether an alternative to v8 with multiple execution tiers such as JavaScriptCore, SpiderMonkey or ChakraCore would obviate the need to jump through heap snapshotting hoops - over in iOS land we are very happy with our startup times since bootstrapping the JavaScriptCore interpreter is way faster than bringing up the optimizing JIT tier. Since v8 lacks an interpreter, it takes longer before it can execute JavaScript code because it has to JIT compile it, right?

**Comment by NathanaelA** [comment]
@fealebenpae - v8 has multiple JIT tiers and an interpreter.  I don't know for sure, but from what I've seen the issue is not bringing up v8 so much as the android/metadata side of things.  This just add an additional speed enhancement.  Can @atanasovg or someone post where the startup time is at?

Using JSC "might" (and that is a big might!) be worth while; because it would mean both platforms would be using the same JS engine.  However, you would have to re-tool several things like the Developer tools would have to be re-worked to work from JSC rather than v8.    Safari isn't supported on Linux or Windows so you have to have something on both those platforms to debug with.

**Comment by borovaka** [comment]
@atanasovg Do you use same approach as Atom's https://github.com/atom/node-mksnapshot?
Can you provide some code sample using this method with NS project?

**Comment by jasssonpet** [comment]
Hello, guys. I'm going to update the issue with the results of a more recent research we did on V8 heap snapshots. Feel free to ask any questions, if something is missing or not quite clear to you.

## Results

Here are the startup times of {N}+Angular on a Nexus 5 device. Only second runs are included, in release configuration.

### {N} Angular hello-world app - [source](https://github.com/hdeshev/bundle-test/blob/a73dc048fe4ac3896a5b8622125701c0f1602b4e/app/app.component.ts)
| Run                                                   | Startup time |
| ----------------------------------------------------- | -----------: |
| non-bundled                                           |       3400ms |
| bundled                                               |       3000ms |
| bundled and snapshotted                               |       2800ms |
| bundled and snapshotted and empty component evaluated |       1550ms |

### {N} Angular render test - [source](https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/renderer-test.ts)
| Run                                                   | Startup time |
| ----------------------------------------------------- | -----------: |
| non-bundled                                           |       4000ms |
| bundled                                               |       3600ms |
| bundled and snapshotted                               |       3400ms |
| bundled and snapshotted and empty component evaluated |       2300ms |

Snapshot size is about 12-16MB (4-6MB when the script is minified).

## Tasks

* Update NativeScript modules to be snapshottable:
  * Refer to this [patch](https://gist.github.com/anonymous/fa490f821d3a86c36bf6cb7fd2b536b5) for the changes.
  * We should figure out how all the `evalLazy` trick would work without a snapshot. The runtime should probably call it immediately after requiring the module.
* JavaScript debugging:
  * At the moment feeding the V8 engine with snapshot data conflicts with registering a debug message handler. We should figure out how to start the debugger properly, so that it can work with snapshot data.
* Research what could be appropriate to be evaluated in the snapshot:
  * Figure out what parts of the Angular infrastructure would be safe to be warmed up.
  * Find a way to evaluate all NativeScript modules.
* Assets extraction:
  * We should measure the performance of extracting the snapshot data blob at runtime.
  * We should figure out how to extract only the snapshot with the current architecture.
  * We should measure the size increase when snapshots are enabled.
  * We should measure the memory overhead when using snapshots, if there is one.
  * Snapshot blobs should be excluded from non-Android builds.
* Resolve `require` calls and `JavaScriptImplementation` annotations from snapshot:
  * Currently we are using [webpack](https://webpack.github.io/) to create the bundle. We should figure out how to map module ids to webpack indices properly.
* Rebuild V8:
  * Both [mksnapshot](https://github.com/NativeScript/android-v8/blob/4.7.80/src/snapshot/mksnapshot.cc#L156) and [nw-snapshot](https://github.com/nwjs/v8/blob/nw12/src/nwjc.cc#L78) call [`CPUFeatures::Probe(bool cross_compile)`](https://github.com/NativeScript/android-v8/blob/4.7.80/src/assembler.h#L206) with the cross-compile flag enabled.
  * Include [this patch](https://github.com/NativeScript/android-v8/commit/e205c1c19e163b50f71642b3a113ab343ee131ab) to report errors during snapshot generation. By default the V8 API only returns `NULL` on error.
  * Measure the possible performance impacts of this. We can use the [Octane benchmark on NativeScript](https://gist.github.com/jasssonpet/20ab386d34a6f89cad0a) for this.

## Optional

* Minification:
  * {N}+Angular has some issues when using minified scripts, like some styles get stripped.
  * The Android static binding generator does not resolve minified Android namespaces. We should figure out a way to reserve the `android` and `java` namespaces when minifying.
* Warmup API:
  * Test how the new [WarmUpSnapshotDataBlob()](https://github.com/NativeScript/android-v8/commit/f507bc1c7242d338b04d6bba5ea78cbb42cf0e13) API is behaving. It seems that it is introducing `enum FunctionCodeHandling { CLEAR_FUNCTION_CODE, KEEP_FUNCTION_CODE };` in the serializer options. This should probably now include compiled code and would make the snapshots even faster. There is some progress here [1](https://github.com/NativeScript/android-v8/commits/5.1.150), [2](https://github.com/NativeScript/android-runtime/commit/d55d557cdbc531cfdb40a44a2f628890bd1137e0).
* Automate snapshot generation:
  * We should figure out how to use the V8 ARM/ARM64 simulator to create a command line tool that generates snapshots during build.
* Find a nice way to report corrupted snapshots:
  * When we update V8, previously generated snapshots would not be compatible with the current runtime. We should have a nice way to report such inconsistencies. A possible solution is to namespace snapshots in folders with the V8 version alongside the architecture.

Ping @atanasovg, @KristinaKoeva.

**P.S.** On the regards of encryption, the heap snapshot turns out to be a poor shot, because the all of the JavaScript source seems to be included inside the snapshot data blob.

**Comment by NathanaelA** [comment]
@jasssonpet Just a FYI, the actual NS runtime (not just angular) has some issues with minifications in the styling system; I ran into this with my NativeScript-Protect; which is one of the reasons I disable minification by default in my encryption system.   I **suspect** the reason why (I haven't traced it fully down yet; since that isn't the purpose of NS-Protect; but because I was curious) and based on some initial tests it looks like the issue is because of the typeName gets set to the wrong name from types.getClass because the minification changes the class names...   This might be the same issue you are seeing with Angular...

Good to know that SnapShots won't eliminate the need for my NS-Protect encryption.  ;-)

**Comment by jasssonpet** [comment]
The repo can be found here: https://github.com/NativeScript/nativescript-angular-snapshot

**Comment by x4080** [comment]
Is the loading performance improvement already in 2.0?

**Comment by jasssonpet** [comment]
@x4080 This is not enabled by default for now, but we are looking for ways to do so in the next release.

**Comment by x4080** [comment]
I see, so in the NS demo app it still not using it yet, I guess ?

**Comment by jasssonpet** [comment]
@x4080 Not yet.

Once we use it there, you can expect the app to start a whole lot faster 😄

**Comment by x4080** [comment]
Alright then

**Comment by jasssonpet** [comment]
I can confirm, that the mksnapshot tool from V8, when cross-compiled for ARM, successfully generates ARM snapshots with the V8 ARM simulator from the host machine, without the need for any ARM devices or emulators :fireworks:

**Comment by NathanaelA** [comment]
@jasssonpet Do we have instructions anywhere on how to use this now and/or any gotchas?

**Comment by jasssonpet** [comment]
Hey @NathanaelA,

You can find more info here:
* https://github.com/NativeScript/android-snapshot
* https://www.npmjs.com/package/nativescript-dev-android-snapshot
