### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#3036]
Improve performance of tns-core-modules by reducing the overhead of the modules.
Here is a list of changes that will improve the speed:
- [x] Change all dependency properties to use the new `Property<T, U>` class
- [ ] Improve binding class by making the happy path as fast as possible (added separate issue: https://github.com/NativeScript/NativeScript/issues/4720)
- [ ] Reuse native views (view recycling) (added separate issue:  #4189 )
- [ ] Instead of reset CSS - reapply the new properties and reset the old ones (added separate issue: https://github.com/NativeScript/NativeScript/issues/4721)
- [x] Remove CSS applying from Page.onLoaded method
- [ ] Check if we could reuse whole {N} views instead only native views (too risky)
- [x] Profile again
- [x] Android: Don't kill native views on forward navigation

**Comment by hamorphis** [comment]
@hshristov Itso, zatvorih tiya issue-ta na koito byah assignat za da si izchista githuba-a -- vie gi re-opennete
