### ISSUE TITLE
[Tracking] AndroidX support

### ISSUE THREAD

**Issue by ADjenkov** [NativeScript/NativeScript#7027]
[Migration to AndroidX draft document](https://docs.google.com/document/d/1HVcVULcB-7wpUniXWyQWJ4qk657KjjSBJ-nocr2dVS4/edit?usp=sharing) 

- [x] (optional) Move [tns-core-modules-widgets](https://github.com/NativeScript/tns-core-modules-widgets) to main [NativeScript repository](https://github.com/NativeScript/NativeScript) (keep as separate packages for the time being)

- [x] Migrate tns-core-modules package to AndroidX:
   - [x] Create branch that uses AndroidX
   - [x] Migrate Apps and Tests apps _(both require published version of `tns-core-modules-widgets@androidX` and `tns-platform-declarations@androidX`)_
   - [x] Migrate support library typings to AndroidX in tns-platform-declarations:
     - [x] Generate androidX-17/23/26/28 `d.ts` files
     - [x] Remove support-library-17/23/26/28 `d.ts` files and deps
   - [x] Publish tns-core-modules@androidx with proper tns-core-modules-widgets@androidx and tns-android@androidx dependencies
   - [x] Publish tns-platform-declarations@androidX package
- [x] Migrate tns-core-modules-widgets package to AndroidX:
   - [x] Create branch that uses AndroidX
   - [x] Publish tns-core-modules-widgets@androidX package
- [ ] {N} Plugins migration:
   - [x] Evaluate and summarize all plugins that use support library
   - [x] Create [migration tool](https://github.com/NativeScript/androidx-migration-tool) that replaces all Support Library namespaces to AndroidX in a project.
   - [x] Migrate [nativescript-ui-listview](https://github.com/NativeScript/nativescript-ui-listview) plugin as a proof-of-concept
   - [x] Migrate the rest of the plugins developed by {N} team
   - [x] Create [sample-androidx-ts](https://github.com/NativeScript/sample-androidx-ts) and [sample-androidx-ng](https://github.com/NativeScript/sample-androidx-ng) repos
   - [x] Create '{N} AndroidX Introduction' Blog/Article
   - [x] Create 'Plugin Migration _Blog/Article_/Steps/Guide' to describe the required migration steps for a plugin that relies on support library:
      -  How to migrate your javascript code?
      -  How to migrate your native code?
      -  How to migrate your 3rd party libraries?
      -  Publish package of your plugin that uses _tns-core-modules@androidX_
      -  Migrate your plugin repo demo apps (if there are any)
   - [x] (optional) Prepare script/tool that migrates (replaces support library namespaces to androidX) java/javascript/xml files to AndroidX
   - [x] (optional) Create PRs that migrates top `nativescript-*` plugins to AndroidX

- [x] Migrate Android Runtime to support AndroidX :
   - [x] Publish dedicated tns-android@androidx package
   - [x] Extend android-dts-generator to support androidX. Add new androidX jar files

- [ ] TODO: Migrate {N} CLI to support AndroidX ?:
