### ISSUE TITLE
[Tracking] Build NativeScript applications using only webpack workflow

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#7320]
## Overview

Webpack is a static module bundler tool and as such is usually the most important part when building the application.

At the moment NativeScript CLI uses two different ways to build the applications
* Using default LiveSync workflow (the legacy workflow)
* Using webpack workflow

Starting with NativeScript 6.0 the legacy workflow will be discontinued and webpack will be the only supported way to build NativeScript applications. This is a list of the remaining tasks within the context of the Modules team.

More info can be found [here](https://www.nativescript.org/blog/the-future-of-building-nativescript-apps).

## Design
Implementation details and motivation of the feature can be found [here](https://progresssoftware-my.sharepoint.com/:w:/g/personal/havaluova_progress_com/EaQ9OfNWg21As0kKjcB5dA8B18Jr0aXz9xayiRhlWlNfag?rtime=rLlrT2rq1kg) (WIP, internal doc for the moment).

### NativeScript 6.0
- [ ] Core modules development workflow should work with bundle workflow
- [ ] Migrate test apps to bundle workflow
  - [ ] Unit tests app
  - [ ] UI tests app
  - [ ] e2e tests apps
  - [ ] Groceries
  - [ ] SDK examples apps
  - [ ] Cuteness
  - [ ] App transitions ?
  - [ ] Animations demo
  - [ ] Background services
  - [ ] Worker loader demo 
  - [ ] QSF
  - [ ] TBD
- [ ] {N} app templates should be migrated to bundle workflow
  - [x] Remove nativescript-dev-sass, nativescript-dev-less and nativescript-dev-typescript; add node-sass, less, typescript as devDependencies where necessary (on branch)
  - [x] Commit tsconfig.json and tsconfig.tns.json in the templates 

### Known issues

- [ ] Broken development workflow with tns-core-modules linked in an application https://github.com/NativeScript/NativeScript/issues/7319
- [ ] Different event order with bundle https://github.com/NativeScript/nativescript-cli/issues/4633
- [ ] Custom xml component tap event does not work when there is no code-behind file https://github.com/NativeScript/nativescript-dev-webpack/issues/865
- [ ] Screen qualifiers not recognized by webpack https://github.com/NativeScript/nativescript-dev-webpack/issues/902
- [ ] Image replacement is not respected with hmr https://github.com/NativeScript/nativescript-cli/issues/4607
- [ ] App restarts with HMR when making changes to node_modules folder https://github.com/NativeScript/nativescript-dev-webpack/issues/899

## Contributing
If you want to work on a task from the list, tell us and we will do our best to help you!
If you have another great idea on how to make the tab view even cooler, share it in the comments!

## Discussion
Please, don't report problems here. Instead, open a new issue and link it to this one.
Let's use this discussion for suggestions and improvement ideas. We would love to hear from you!

**Comment by NathanaelA** [comment]
https://github.com/NativeScript/nativescript-dev-webpack/issues/921 - is also another breaking change.   Solution is provided in the issue; but needs the webpack config files changed...

**Comment by edusperoni** [comment]
If the core team could please take a look at https://github.com/NativeScript/worker-loader/pull/39, I believe it'll be required for using `workers` with angular (and other plugins)
