### ISSUE TITLE
[Tracking] iOS13 Support

### ISSUE THREAD

**Issue by manoldonev** [NativeScript/NativeScript#7868]
## Overview
It seems iOS 13 brought lots of breaking / behavior changes to lots of UIKit components. We are creating this issue to track the issues and the progress of their resolution.

## Tasks

Issues:
- [ ] [BottomNav] Incorrect color applied to text in iOS 13 - #7862
- [ ] [BottomNav] Styling is completely messed up on device rotation - #7864
- [ ] [SegmentedBar] Component has changed look & feel - #7850
- [ ] [Modal] New modal view style does not clean up when swiped to close - #7846
- [ ] [TabView] Buttons incorrect alignment - #7767

## Contributing
If you want to work on a task from the list, tell us and we will do our best to help you!
If you have another great idea on how to make the tab view even cooler, share it in the comments!

## Discussion
Please, don't report problems here. Instead, open a new issue and link it to this one.
Let's use this discussion for suggestions and improvement ideas. We would love to hear from you!

**Comment by VladimirAmiorkov** [comment]
Here is an issue related to iOS 13 and the ActionBar which can be observed with RadSideDrawer:
https://github.com/NativeScript/nativescript-ui-feedback/issues/1265
