### ISSUE TITLE
[Tracking] Scoped Packages

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#7895]
Original issue/idea discussed in #4041
[Link to design document](https://docs.google.com/document/d/1ifC9f6hlw9gedd7K8DUQ43AUjryes7G4B3i7Fhkdxck/edit?usp=sharing)

- [ ] `@nativescript/core` package
  - [ ]  Move all the code to `@nativescript/core` generate the `tns-core-modules` compatibility package
  - [ ] generate tests that validate that compatibility package exports all modules
  - [ ] Update developer workflow. There shoould be an easy way to setup the `nativescript/nativescrit` repo so that you can run the `tests` and all `e2e` projects with linked modules and HMR.
  - [ ] Do a detailed review of the barrel exports:
    - [ ] [`@nativescript/core`](https://github.com/NativeScript/NativeScript/blob/scoped-packages-generate-master/nativescript-core/index.ts)
    - [ ] [`@nativescript/core`](https://github.com/NativeScript/NativeScript/blob/scoped-packages-generate-master/nativescript-core/ui/index.ts)
    - [ ] [`@nativescript/core/ui/layouts`](https://github.com/NativeScript/NativeScript/blob/scoped-packages-generate-master/nativescript-core/ui/layouts/index.ts)
    - [ ] Missing modules. Style, FormattedString etc.
       - `Styling` -> there are a couple of useful things from styling modules:
       `export { addTaggedAdditionalCSS, removeTaggedAdditionalCSS } from "./styling/style-scope";`
        `export { Style } from "./styling/style";`
       - `FormattedString`, `Text`, `Span`
  - [ ] Rethink the `ns` prefix for and whether it is the right choice for all. 
    - Problematic modules: `ImageSource`, `Frame`, `application`. They have both classes and methods
    - Should we use the ns prefix at all (`trace` vs `nsTrace`)
  - [ ] generate documentation (with typedoc) for the scoped packages. 
    - Will research if we can generate typedoc for barrel files (seems now that re-exported modules are not documented)

- [ ] `@nativescript/angular` package
  - [ ] Move all the code to `@nativescript/angular` and create `nativescript-angular` compatibility package (either generate it or manually create it)
  - [ ] ...

- [ ] `nativescript-dev-webpack` package
  - [ ] Remove the `tns-core-module/xml` dependency in the `xml-namespace-loader`
  - [ ] Make sure webpack works with the `tns-core-modules` compatibility package without the need to change configuration. 

- [ ] `nativescript-cli`
  - [ ] ...
