### ISSUE TITLE
CI and polishing nativescript-background-http

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#896]
- [x] CI

Consider the issues in the "nativescript-background-http" plugin:
 - [x] [Project scaffolding - tests, docs, d.ts-es](https://github.com/NativeScript/nativescript-background-http/issues/1)
 - [ ] [Service id, depends on the plugin parameters CLI feature](https://github.com/NativeScript/nativescript-background-http/issues/5)
 - [x] [Support both URIs and file paths for iOS tasks](https://github.com/NativeScript/nativescript-background-http/issues/6)
